CREATE TABLE `supplier_config` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `supplier_code` VARCHAR(50) NOT NULL UNIQUE COMMENT '供应商唯一标识,如 ALI_YUN',
    `supplier_name` VARCHAR(100) NOT NULL COMMENT '供应商业务名称',
    `description` VARCHAR(255) DEFAULT NULL COMMENT '供应商备注说明,供运维人员标记用途或注意事项',
    `base_url` VARCHAR(128) NOT NULL COMMENT '目标域名主体,如 https://api.sms.com',
    `http_method` VARCHAR(10) NOT NULL DEFAULT 'POST' COMMENT 'HTTP请求方法: POST, PUT, PATCH, GET',
    `content_type_behavior` VARCHAR(32) NOT NULL DEFAULT 'APPLICATION_JSON' COMMENT '报文类型行为: APPLICATION_JSON, APPLICATION_FORM_URLENCODED',
    `credentials_encrypted` TEXT DEFAULT NULL COMMENT '供应商敏感凭证密文(AES-256-GCM加密),JSON结构存储appSecret/signingKey等,运行时由CredentialVault解密后注入UnifiedInputContext.auth',
    `path_template` VARCHAR(255) DEFAULT NULL COMMENT 'JSONata格式的动态Path模板,为空时使用base_url原始路径',
    `query_template` TEXT DEFAULT NULL COMMENT 'JSONata格式的Query参数模板,为空时不追加查询参数',
    `header_template` TEXT DEFAULT NULL COMMENT 'JSONata格式的Header模板,为空时仅携带Content-Type等默认头',
    `body_template` TEXT NOT NULL COMMENT 'JSONata格式的Body模板',
    `connect_timeout_ms` INT NOT NULL DEFAULT 3000 COMMENT '连接超时时间(毫秒)',
    `read_timeout_ms` INT NOT NULL DEFAULT 5000 COMMENT '读取超时时间(毫秒)',
    `success_http_codes` VARCHAR(50) DEFAULT '200' COMMENT '成功HTTP状态码,逗号分隔',
    `success_body_pattern` VARCHAR(255) DEFAULT NULL COMMENT '响应体匹配表达式',
    `success_body_match_mode` VARCHAR(20) DEFAULT 'EQUALS' COMMENT '匹配模式: EQUALS/CONTAINS',
    `success_case_sensitive` TINYINT DEFAULT 1 COMMENT '是否大小写敏感: 1-是, 0-否',
    `max_retry_count` INT NOT NULL DEFAULT 3 COMMENT '最大重试上限次数',
    `retry_backoff_initial_ms` INT NOT NULL DEFAULT 1000 COMMENT '退避重试初始延迟(毫秒),如1000ms',
    `retry_backoff_multiplier` DECIMAL(3,2) NOT NULL DEFAULT 2.00 COMMENT '退避重试指数乘数/倍数,如2.00倍演进',
    `retry_backoff_max_ms` INT NOT NULL DEFAULT 30000 COMMENT '退避重试最大延迟封顶上限(毫秒),防止无限制放大延迟',
    `worker_concurrency` INT NOT NULL DEFAULT 1 COMMENT '该供应商的消费线程并发数,高流量渠道可设>1,线程总数受max-worker-threads硬上限约束',
    `status` TINYINT DEFAULT 1 COMMENT '状态: 1-启用, 0-禁用',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间(审计与缓存刷新凭据)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='中台防腐层供应商核心配置表';
