CREATE TABLE `subscription` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `subscriber_code` VARCHAR(64) NOT NULL COMMENT '订阅方编码(对应 supplier_config.supplier_code)',
    `event_type_code` VARCHAR(128) NOT NULL COMMENT '事件类型编码',
    `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/SUSPENDED',
    `managed_by` VARCHAR(16) NOT NULL DEFAULT 'SUBSCRIBER' COMMENT '管理方: SUBSCRIBER/PUBLISHER/PLATFORM',
    `path_template` VARCHAR(255) DEFAULT NULL COMMENT '覆盖:JSONata Path模板',
    `query_template` TEXT DEFAULT NULL COMMENT '覆盖:JSONata Query模板',
    `header_template` TEXT DEFAULT NULL COMMENT '覆盖:JSONata Header模板',
    `body_template` TEXT DEFAULT NULL COMMENT '覆盖:JSONata Body模板',
    `connect_timeout_ms` INT DEFAULT NULL COMMENT '覆盖:连接超时(ms)',
    `read_timeout_ms` INT DEFAULT NULL COMMENT '覆盖:读取超时(ms)',
    `max_retry_count` INT DEFAULT NULL COMMENT '覆盖:最大重试次数',
    `retry_backoff_initial_ms` INT DEFAULT NULL COMMENT '覆盖:退避初始延迟(ms)',
    `retry_backoff_multiplier` DECIMAL(5,2) DEFAULT NULL COMMENT '覆盖:退避指数乘数',
    `retry_backoff_max_ms` INT DEFAULT NULL COMMENT '覆盖:退避最大延迟(ms)',
    `success_http_codes` VARCHAR(64) DEFAULT NULL COMMENT '覆盖:成功HTTP状态码',
    `success_body_pattern` VARCHAR(512) DEFAULT NULL COMMENT '覆盖:响应体匹配表达式',
    `success_body_match_mode` VARCHAR(16) DEFAULT NULL COMMENT '覆盖:匹配模式',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    UNIQUE KEY `uk_subscriber_event` (`subscriber_code`, `event_type_code`),
    INDEX `idx_event_type_code` (`event_type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订阅关系表';
